package dadkvs.server;


import java.util.ArrayList;
import java.util.Iterator;

/* these imported classes are generated by the contract */
import dadkvs.DadkvsMain;
import dadkvs.DadkvsPaxos;
import dadkvs.DadkvsPaxosServiceGrpc;

import dadkvs.util.GenericResponseCollector;
import dadkvs.util.CollectorStreamObserver;

import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.stub.StreamObserver;

import dadkvs.util.GenericResponseCollector;
import dadkvs.util.CollectorStreamObserver;

public class DadkvsPaxosServiceImpl extends DadkvsPaxosServiceGrpc.DadkvsPaxosServiceImplBase {


    DadkvsServerState server_state;
    
    
    public DadkvsPaxosServiceImpl(DadkvsServerState state) {
	this.server_state = state;
	
    }
    

    @Override
    public void phaseone(DadkvsPaxos.PhaseOneRequest request, StreamObserver<DadkvsPaxos.PhaseOneReply> responseObserver) {
	// for debug purposes
	System.out.println("Receive phase1 request: " + request);
    if(!server_state.i_am_leader){
        //verificar se timestamp recebido e maior doq aquele q ja tenho
        System.out.println("Received phase one request for index : " + request.getPhase1Index() + " with timestamp: " + request.getPhase1Timestamp());
        boolean accepted = true;
        int accepted_value = server_state.agreed_indexes.getOrDefault(request.getPhase1Index(), -1);
        if(server_state.timestamp > request.getPhase1Timestamp()){
            accepted = false;
            //responder recusando
            System.out.println("Will refuse the request");
        }else{
            server_state.timestamp = request.getPhase1Timestamp();
        }
        DadkvsPaxos.PhaseOneReply.Builder phase_one_reply = DadkvsPaxos.PhaseOneReply.newBuilder();
				phase_one_reply.setPhase1Config(request.getPhase1Config())
						.setPhase1Index(request.getPhase1Index())
						.setPhase1Timestamp(server_state.timestamp)
                        .setPhase1Accepted(accepted)
                        .setPhase1Value(accepted_value)
                        .build();
        responseObserver.onNext(phase_one_reply.build());
        responseObserver.onCompleted();
        //enviar resposta
    }
    else{
        ;
        // wait for x messages

        // send phasse 2 messages

    }

    }

    @Override
    public void phasetwo(DadkvsPaxos.PhaseTwoRequest request, StreamObserver<DadkvsPaxos.PhaseTwoReply> responseObserver) {
        // for debug purposes
        System.out.println ("Receive phase two request: " + request);
        boolean accepted = true;
        if(!server_state.i_am_leader){
            System.out.println("Received phase two request for index : " + request.getPhase2Index() + " with timestamp: " + request.getPhase2Timestamp());
            if(server_state.timestamp > request.getPhase2Timestamp()){
                accepted = false;
            }else{
                server_state.agreed_indexes.put(request.getPhase2Index(),request.getPhase2Value()); //marcar como guardado
            }
            DadkvsPaxos.PhaseTwoReply.Builder phase_two_reply = DadkvsPaxos.PhaseTwoReply.newBuilder();
            phase_two_reply.setPhase2Config(request.getPhase2Config())
                    .setPhase2Index(request.getPhase2Index())
                    .setPhase2Accepted(accepted)
                    .build();
        responseObserver.onNext(phase_two_reply.build());
        responseObserver.onCompleted();
        }
    }

    @Override
    public void learn(DadkvsPaxos.LearnRequest request, StreamObserver<DadkvsPaxos.LearnReply> responseObserver) {
	// for debug purposes
	System.out.println("Receive learn request: " + request);
    boolean accepted = true;
    if(request.getLearntimestamp() < server_state.timestamp){
        accepted = false;
    }
    DadkvsPaxos.LearnReply.Builder learn_reply = DadkvsPaxos.LearnReply.newBuilder();
    learn_reply.setLearnconfig(request.getLearnconfig())
            .setLearnindex(request.getLearnindex())
            .setLearnaccepted(accepted)
            .build();
responseObserver.onNext(learn_reply.build());
responseObserver.onCompleted();
    DadkvsMainServiceImpl.executeCommit(request.getLearnvalue(), server_state);
    responseObserver.onNext(learn_reply.build());
    responseObserver.onCompleted();

    }

    

}
